name: Build and Validate Code
run-name: ${{ github.actor }} is building and validating code
on: [push]
jobs:
    Validate-TF:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Listing files in the repo
              run: |
                ls ${{ github.workspace }}
            - name: Install OpenTofu
              uses: opentofu/setup-opentofu@v1

            - name: Validate Terraform code
              working-directory: ./terraform
              run: |
                tofu init && tofu validate

            